
# https://megalinter.io/latest/supported-linters/
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  #- GO_GOLANGCI_LINT # disabled because it fails on multi-module repository
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - PROTOBUF_PROTOLINT
  - REPOSITORY_GITLEAKS
  #- REPOSITORY_KICS
  - YAML_YAMLLINT
REPOSITORY_KICS_ARGUMENTS: "--fail-on high"
