// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Enrich telemetry attributes with compliance control data
	// (POST /v1/enrich)
	PostV1Enrich(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostV1Enrich operation middleware
func (siw *ServerInterfaceWrapper) PostV1Enrich(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Enrich(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/enrich", wrapper.PostV1Enrich)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYXXPbuhH9Kxi0M21nKFlO+jV681WSuZ7pvVYt377EfoDAlYQYBBjsUo6a8X/vLAiK",
	"H6LsZNL7JhFY4Ozu2d1DfpXaF6V34Ajl/KtEvYNCxZ8LX5TWKKeB/6k8N2S8U3YZfAmBDKCcb5RFyGQO",
	"qIMpeV3OO4YiB1LGotgEX4ibxeqDWIGugqGDWHhHwVuxDH5jLExlJsvOyQwsbuCffwywkXP5h4sW7EVC",
	"etHelk6Uz5kEF4zeFeBoRYqqeF4fZP1c+I2gHQjdQm5NRRm8BsS5WFWaf2TiN1eosoQ8E0sVyCjLjx6d",
	"f3KZ8EGsHg2vsi/gqkLOP8pkKjPZ2MpMJuP4MFrLTCZb+ZBJ+KKK0gKjPFrToeQHSMG4Lbu4CaqAJx8e",
	"8dsj9KG1ec5kMPj47ba3vPuZzeBzZQLk7F2Tox6ckfA/ZJIMRZc6tDp65defQBNjOs3maeYaBqXLhXEb",
	"HwrFy2LjQzeZChEQGcgJvVRZWqPV2lhDh9Nb3ru9Cd6xKYp4qCP4QiiedhBA0M7gEUA8CqLjTeY+ymXw",
	"eaXjaRmzbct5e8ikISgigJOMpgcqBHXg/1qRsn57nZ+i+82ZzxUIk4MjszEQouPMZBxGJ53CPhxz1EUq",
	"b1bL1eSnMYppRbD1YSQ6i7QST1WFsQdBO0XjCNZgvduiIN+79ypSu+kDY/ebH/N8DcZtEwVi2Q18/vfV",
	"ZPaP6exy7OoABeQmcupd9/4hnM5i00sCaF8U4HLIRecYgRQ4aocEuOVPD9ktFH4PInhPokIIQtVhUi4X",
	"hvc0namEIK6vfhGlt0bX7Bt4MahVwyFoOdVJ78OLhfih12jOtvojuSLUdHEE26nPkyrcvHD4LWwrqyjR",
	"zLi8QgoHgaRcrkKOKcGwV7ZSBPmg+Pvl+Ov16m7yz9ls8re3XI83i8mb76vGjkcvB6Ln+pGmaQYyQVqf",
	"hx70IV8tJszNxeLv08vvwTrIe68z97x4Oe+3aTycd9TgY6fDvphnC3sY6eV8h4hrfJDXJubxydBOOO8m",
	"/WSmiboIhoyO0/Nns93JTP4CuakKmcl/+SeZyesWh7L9eZoMXi6UGutYcN4f59otfK4AaYy0cUGU6mC9",
	"qjlJwGXL3FVEwawr6sqMk1jFij68NpmX9a4h+GT8GnosvUM4k16gniIqgFSuSAnjtK1yZmzTYlnRGLfF",
	"rEPqbEiMaZfWteBsdWVH5Q0m8vkR2hmM7fRqh9XpZDH5SM8/1+J/oAWPKs+OiOt3u+6/sw2q33aGTaGj",
	"4lKF1RR/ZloM5XQ37N+m+Ub03nFplGEh+BApPLg6H6Haz3d3S27mLMPjjg5L/jqbZbKuYjmXxtHbN23Z",
	"GkewhcAXFoCotiOHRySiWX6t4tP1zfYx15bHojxTMLDnZq9BsNiKvb4uRQFuaxzU9BmVpoK8t3imDbyP",
	"1r+qYsRJftqojt5ltRgrIXAIIY8b0pCJQiUI4B6payarpsQ6+mh5NaaK6ktuKwvfJ0oTuFBZOBnaLZi+",
	"RMvBHSZcgxOuwVdTeBKtAdrTnPIJPLJOHbkSGhwFZc1/IR/thAhhDyGFOXhOPSYvJ+QnXZOmQ967pml2",
	"W2XUSv12iTFs6TCFEyan4O0b659wKu5YOjIAo6EGgkLhveNAq4p2PhhSZPYg0FeBlVn/nahxIhPg1Npy",
	"Nm5KcHfHIaW9taDJh5qznnYQ7h0ekPWHIJ9m15FyLbFgH/HH+d3ItGEM04tUdu9Cq+/aOXIMiLYK0WyM",
	"jkfj9J4Z2n2JVIhilcJwtbyWmdxDwDqDs+nldMaM9SU4VRo5l2+nsyl31lLRLtbXxf7yovakrraxac6T",
	"pCQUnHHiUnuEw9g4R/FnmG6nWUwjiet3WRMdpwrI6jFy/e4v7B47TlVwKNpvKp0ATQLYWBidw9cKuVKc",
	"4NYXeH/uC2Uc9xqjp/cucgJcXnrDQgzjxvgGQl6sQWhlLeRifRDKDbK9aLL9JxS6QuLGVX/38KEOOjel",
	"mIQ4cJce6T+XtZZIghKQfvL5oRnnrGnacc6GF5+wfnmqR8xrA+hUZj33y51CBfFBLWNiOt/MZr8LgKSU",
	"IoLBh4h6rm8qaw+pJnppk9FioypL/z9kccKOgKkcfClBM3Eg7ckkVkWhoiSqPRqnbizXQYVyn+ImwVc9",
	"/y8AAP//owzEwCUUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
